version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: personService
    environment:
      MYSQL_ROOT_PASSWORD: 12321232
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge